CC=gcc
CFLAGS=-Wall
LDLIBS=-lmd

OBJECTS=client2.o server2.o
SOURCES=client2.c server2.c

#what make does by default
#.c:
#$(CC) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS) $(TARGET_ARCH) $^ $(LOADLIBES) $(LDLIBS) -o $@

both: $(OBJECTS)
        $(CC) $(SOURCES) -o $@ client server $(LDLIBS) #$^:


clean:
    rm -f *~ *.o client server



